use mydb;
delete from `auditor bid`;
delete from auditor;
delete from bid;
delete from `buy history`;
delete from `sale history`;
delete from history;
delete from `buyer list`;
delete from offers;
delete from bid;
delete from `seller list`;
delete from `buyer list`;
delete from `game owner`;
delete from user;
delete from `game`;